# Change database name, then run "rake db:create db:migrate"

defaults: &defaults
  adapter: mysql2
  encoding: utf8
  username: tlils
  password: 
  pool: 5
  host: localhost
  reconnect: true

development:
  <<: *defaults
  database: wedding_dev

test: &test
  <<: *defaults
  database: wedding_test

cucumber:
  <<: *test

production:
 <<: *defaults
 database: <%= ENV['RDS_DB_NAME'] %>
 username: <%= ENV['RDS_USERNAME'] %>
 password: <%= ENV['RDS_PASSWORD'] %>
 host: <%= ENV['RDS_HOSTNAME'] %>
 port: <%= ENV['RDS_PORT'] %>
